spring:
  datasource:
    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 25
        connection:
          provider_disables_autocommit: true
        default_batch_fetch_size: 50
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    web:
      pageable:
        max-page-size: 50
  docker:
    compose:
      enabled: false

springdoc:
  swagger-ui:
    path: /
    url: /open-api-v1.json
