server:
  address: 127.0.0.1
  port: 8086
  ssl:
    enabled: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/documents?reWriteBatchedInserts=true
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  template:
    provider:
      cache: false
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
        period: 0
      chain:
        cache: false
  mail:
    host: dev
    port: 587
    username: dev
    password: dev
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE

s3:
  endpoint: http://127.0.0.1:9000
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  common-bucket: documentflow
  draft-bucket: documentflow-temp
  min-content-length: 0
  max-content-length: 1048576
  draft-expiration-days: 1
  upload-expiration-minutes: 720
  download-expiration-minutes: 720

email-client:
  sender-address: ${EMAIL_SENDER_ADDRESS}
